services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/app/dist
    ports:
      - "8443:8443"
    networks:
      - matcha

volumes:
  frontend_dist:

networks:
  nginx_data:
    driver: local
  matcha:
    driver: bridge
